"""Add test_field column to search_history table

Revision ID: 91e863408a95
Revises: 92a1d37c5117
Create Date: 2024-11-20 22:06:38.459620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e863408a95'
down_revision: Union[str, None] = '92a1d37c5117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('test_field', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'test_field')
    # ### end Alembic commands ###
